[package]
name = "wimg-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.0-rc.7", features = ["derive"] }
hex = "0.4"
log = "0.4"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wimg = { path = "../../wasm/wimg" }
